# Stage 1: Base stage
FROM debian:buster-slim AS base

LABEL description="Corosync Qdevice Network daemon"
LABEL documentation="man:corosync-qnetd"

# Install necessary dependencies
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        ca-certificates \
        gnupg \
        adduser \
        && rm -rf /var/lib/apt/lists/*

# Install the proxmox repository signing key.
ADD "https://enterprise.proxmox.com/debian/proxmox-ve-release-6.x.gpg" \
    /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg

# Add Proxmox repository
RUN echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" \
    > /etc/apt/sources.list.d/corosync3.list

# Stage 2: Install corosync-qnetd
FROM base AS install

# Create the coroqnetd user and group
RUN adduser --quiet --system --disabled-login --no-create-home \
        --home /etc/corosync/qnetd --group --uid=903 coroqnetd

# Set permissions
RUN chmod 1777 /var/run \
    && chmod a+r /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg

# Install corosync-qnetd
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        corosync-qnetd \
        openssh-server \
    && rm -rf /var/lib/apt/lists/*

# Create necessary directories
RUN mkdir -p /etc/corosync/qnetd/nssdb \
    && touch /etc/corosync/qnetd/nssdb/cert9.db

# Stage 3: Final stage
FROM base AS final

# Copy corosync-qnetd and start script
COPY --from=install /usr/local/bin/start-coroqnetd /usr/local/bin/start-coroqnetd
COPY --from=install /etc/corosync /etc/corosync

# Set permissions
RUN chmod +x /usr/local/bin/start-coroqnetd

# Set healthcheck command
HEALTHCHECK CMD corosync-qnetd-tool -s

# Set user
USER 903:903

# Expose port
EXPOSE 5403

# Set umask
ENV UMASK=

# Set corosync-qnetd options
ENV COROSYNC_QNETD_OPTIONS=

# Set default command
CMD ["start-coroqnetd"]
ENTRYPOINT ["start-coroqnetd"]
