# Define the directory of the script
DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" >/dev/null 2>&1 && pwd )"

# alias contruction
#
# Common directories
LIB_DIR="$DIR/../lib"
SET_DIR="$DIR/../set"
VAR_DIR="$DIR/../var"
DOT_DIR="$DIR/../dot"
TOO_DIR="$DIR/../too"

# Source necessary scripts
source "$LIB_DIR/all.bash"
source "$LIB_DIR/ost.bash"
source "$LIB_DIR/pve.bash"

# Define arrays for constructing aliases
#
files=(all ost pve pbs shr)
bash_files=(all ost pve pbs shr)

# Generate bash execution aliases
for file in "${bash_files[@]}"; do
  alias "b.$file.sh"="bash $SET_DIR/$file.sh"
done

# Generate cat aliases
for file in "${files[@]}"; do
  alias "c.$file.bash"="cat $LIB_DIR/$file.bash"
  alias "c.$file.sh"="cat $SET_DIR/$file.sh"
  alias "c.$file.conf"="cat $VAR_DIR/$file.conf"
done
alias c.b="cat $DOT_DIR/bashrc"

# Generate vim aliases
for file in "${files[@]}"; do
  alias "v.$file.bash"="vim $LIB_DIR/$file.bash"
  alias "v.$file.sh"="vim $SET_DIR/$file.sh"
  alias "v.$file.conf"="vim $VAR_DIR/$file.conf"
done
alias v.b="vim $DOT_DIR/bashrc"

# hardcoded section
#
# standard
alias b='bash'
alias c='cat'
alias d='cd'
alias g='git'
alias v='vim'

# directory selection
alias ..='cd ..'
alias d.l="cd $DIR/.."
alias d.samba='cd /etc/samba/'
alias d.snapper='cd /etc/snapper/configs'
alias d.pam='cd /usr.bash/pam_snapper'

# filesystem management
alias b='btrfs'
alias bf='btrfs filesystem'

# system configuration
alias v.smb.conf='vim /etc/samba/smb.conf'
alias v.smbusers='vim /etc/samba/smbusers'
alias v.firewall.conf='vim /etc/firewalld/firewalld.conf'
alias v.fstab='vim /etc/fstab'

# git management
alias gl='git ls-files | xargs cat | wc -l'
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m "standard"'
alias go='git push origin master'
alias gp='git pull'

# System control aliases
alias s='sudo'
alias y='systemctl'

# Utility aliases
alias ee='exit'
alias eb='exec bash'
alias h='history'

# Disk usage aliases
alias u='du -bh -d1'
alias uu='du -bh -d2'
alias uuu='du -bh -d3'

# Tree view aliases
alias t='tree'
alias tt='tree -L 2'
alias ttt='tree -L 3'
alias tttt='tree -L 4'
alias ttttt='tree -L 5'

# Transactional update alias
alias tu='transactional-update'

# Sysstat
alias sar='sar -d 1'
alias ios='iostat -x 1'
