#!/bin/bash

# Main configuration file
# This file sources the modular components and handles the main execution

# Define the directory of the script using a POSIX-compliant method
DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" >/dev/null 2>&1 && pwd )"
PARENT_DIR="$DIR/.."

# Source modular components
source "$DIR/rc0"
source "$DIR/rc1"
source "$DIR/rc2"
source "$DIR/rc3"

# Main execution
main() {
    # Call functions from modules

    #rc1
    setup_aliases
    #rc2
    setup_navigation
    #rc3
    setup_environment
}

# Execute main function
main
