#!/bin/bash

# rc2 module

setup_static_functions() {
    # Setup SSH keys and create aliases
    setup_ssh() {
        add_ssh_keys
        # SSH aliases
        alias sk.ed='ssh-keygen -t ed25519 -C "woeiru/lab"'
        alias sc.ed='ssh-copy-id -i ~/.ssh/id_ed25519.pub root@$SSH_TARGET_IP'
    }

    # Add SSH keys to the agent
    add_ssh_keys() {
        if [ -z "$SSH_AUTH_SOCK" ]; then
            eval "$(ssh-agent -s)" > /dev/null || echo "Failed to start ssh-agent" >&2
        fi
        local keys=(
            "$HOME/.ssh/id_rsa"
            "$HOME/.ssh/id_ed25519"
            "$HOME/.ssh/w1"
        )
        for key in "${keys[@]}"; do
            if [[ -f "$key" && ! $(ssh-add -l | grep -q "$(ssh-keygen -lf "$key" | awk '{print $2}')") ]]; then
                ssh-add "$key" || echo "Failed to add key: $key" >&2
            fi
        done
    }

    # List all SSH keys in the agent
    list_ssh_keys() {
        ssh-add -l || echo "No keys found or ssh-agent is not running" >&2
    }

    # Remove all SSH keys from the agent
    remove_ssh_keys() {
        ssh-add -D || echo "Failed to remove SSH keys" >&2
    }

    # Call the functions
    setup_ssh
    list_ssh_keys
}
