#!/bin/bash
# rc3 - Alias Management

# Master toggle for alias wrapping functionality
AW_TOGGLE=false

# Set up a function to wrap alias execution with error trapping
aliaswrap() {
    if $AW_TOGGLE; then
        echo "Executing command: $*"
        trap 'echo "Error occurred on line $LINENO"; return 1' ERR
        "$@"
    else
        "$@"
    fi
}

# Wrap all aliases with the error trapping function
set_aliaswrap() {
    if $AW_TOGGLE; then
        echo ""
        echo -e "Starting \033[1m ${FUNCNAME[0]} () \033[0m"
        while read -r alias_def; do
            if [[ $alias_def =~ ^alias\ ([^=]+)=(.*)$ ]]; then
                alias_name="${BASH_REMATCH[1]}"
                alias_command="${BASH_REMATCH[2]}"
                # Remove surrounding quotes if present
                alias_command="${alias_command#[\'\"]}"
                alias_command="${alias_command%[\'\"]}"
                alias "$alias_name"="aliaswrap $alias_command"
            fi
        done < <(alias)
        log "LVL1" "All aliases have been wrapped with error trapping."
    else
        echo "Alias wrapping is disabled."
    fi
}

# Export functions
export -f aliaswrap
export -f set_aliaswrap
