# Use Debian 12 as the base image
FROM debian:12

# Define build arguments for the username and password
ARG USERNAME=xo
ARG PASSWORD=password
ARG UID=1000
ARG GID=1000

# Install Samba and other necessary packages
RUN apt-get update && \
    apt-get install -y samba && \
    apt-get clean

# Expose SMB ports
EXPOSE 139 445

# Create the group with GID
RUN groupadd -g $GID $USERNAME

# Create the user with UID and add to the group
RUN useradd -u $UID -g $GID -d /home/$USERNAME -s /bin/sh $USERNAME && \
    mkdir -p /home/$USERNAME && \
    chown -R $USERNAME:$USERNAME /home/$USERNAME && \
    chmod 777 /home/$USERNAME && \
    echo "$USERNAME:$PASSWORD" | chpasswd

# Set Samba password for the user
RUN echo "$PASSWORD\n$PASSWORD" | smbpasswd -a -s $USERNAME

# Copy custom smb.conf to the container
COPY smb.conf /etc/samba/smb.conf

# Start the Samba service
CMD ["smbd", "-F", "--no-process-group"]
