---
- name: Ensure .local/share/konsole directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/share/konsole"
    state: directory
    mode: '0755'

- name: Copy Konsole Profile 1
  copy:
    src: konsole_profile_1.profile
    dest: "{{ ansible_env.HOME }}/.local/share/konsole/Profile 1.profile"
    mode: '0644'

- name: Copy Konsole Profile 2
  copy:
    src: konsole_profile_2.profile
    dest: "{{ ansible_env.HOME }}/.local/share/konsole/Profile 2.profile"
    mode: '0644'
