---
- name: Ensure .local/share/konsole directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/share/konsole"
    state: directory
    mode: '0755'

- name: Create Konsole Profile 1
  copy:
    content: |
      [Appearance]
      ColorScheme=SolarizedLight
      Font=Noto Sans Mono,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1

      [General]
      Name=Profile 1
      Parent=FALLBACK/
      TerminalColumns=133
      TerminalRows=44
    dest: "{{ ansible_env.HOME }}/.local/share/konsole/Profile 1.profile"
    mode: '0644'

- name: Create Konsole Profile 2
  copy:
    content: |
      [Appearance]
      ColorScheme=Linux
      Font=Noto Sans Mono,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1

      [General]
      Name=Profile 2
      Parent=FALLBACK/
      TerminalColumns=133
      TerminalRows=144
    dest: "{{ ansible_env.HOME }}/.local/share/konsole/Profile 2.profile"
    mode: '0644'
