# Define the directory of the script
DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" >/dev/null 2>&1 && pwd )"

# alias contruction
#

# Common directories
#
PARENT_DIR="$DIR/.."

for dir in "$PARENT_DIR"/*; do
    if [ -d "$dir" ]; then
        base=$(basename "$dir")
        if [ ${#base} -eq 3 ]; then
            var_name="${base^^}_DIR"
            declare "$var_name=$dir"
            alias "d.$base=cd $dir"
        fi
    fi
done

# Define arrays for constructing aliases
#
files=(all osm pbs pve nfs smb)
bash_files=(all osm pbs pve nfs smb)

# Source necessary scripts
for file in "${files[@]}"; do
   source "$LIB_DIR/$file.bash"
done

# Generate variable overview aliases
for file in "${files[@]}"; do
   alias var.$file="all-acu o /root/lab /root/lab/var/$file.conf"
done

# Generate bash execution aliases
for file in "${bash_files[@]}"; do
  alias "b.$file.sh"="bash $SET_DIR/$file.sh"
done

# Generate cat aliases
for file in "${files[@]}"; do
  alias "c.$file.bash"="cat $LIB_DIR/$file.bash"
  alias "c.$file.sh"="cat $SET_DIR/$file.sh"
  alias "c.$file.conf"="cat $VAR_DIR/$file.conf"
done

# Generate vim aliases
for file in "${files[@]}"; do
  alias "v.$file.bash"="vim $LIB_DIR/$file.bash"
  alias "v.$file.sh"="vim $SET_DIR/$file.sh"
  alias "v.$file.conf"="vim $VAR_DIR/$file.conf"
done

# Generate aliases for all folders containing the specified file in the entire repo
FILEBASE_MD="readme.md"
while IFS= read -r -d '' file; do
  dir=$(dirname "$file")
  alias_name=$(basename "$dir").md
  alias "c.$alias_name"="cat $file"
  alias "v.$alias_name"="vim $file"
done < <(find "$DIR/.." -type f -name "$FILEBASE_MD" -print0)


# function chains
#
alias fun='all-ffl all-laf "" /root/lab/lib'
alias var='all-ffl all-acu "" /root/lab/var /root/lab/'

# function aliases
alias sca='all-sca'
alias flc='all-flc'
alias cto='pve-cto'

# standard aliases
#

# bash
alias b='bash'
alias eb='exec bash'

# btrfs management
alias bt='btrfs'
alias btf='btrfs filesystem'

# cat
alias c='cat'
alias c.b="cat $INI_DIR/bashrc"
alias c.group='cat /etc/group'
alias c.passwd='cat /etc/passwd'
alias c.fstab='cat /etc/fstab'
alias es.log='cat /mnt/bak/home/.es.log'

# directory selection
alias d='cd'
alias ..='cd ..'
alias dl="cd $DIR/.."

alias d.samba='cd /etc/samba/'
alias d.snapper='cd /etc/snapper/configs'
alias d.pam='cd /usr/lib/pam_snapper'

alias d.das='cd /mnt/das'
alias d.nvm='cd /mnt/nvm'
alias d.usb='cd /mnt/nvm'

# disk usage aliases
alias u='du -bh -d1'
alias uu='du -bh -d2'
alias uuu='du -bh -d3'

# exits
alias ee='exit'

# git
alias g='git status'
alias gd='git diff'
alias gl='git ls-files | xargs cat | wc -l'
alias ga='git add .'
alias gc='git commit -m "standard"'
alias go='git push origin master'
alias gp='git pull'
alias gg='all-gio'
alias gr1='git revert HEAD~1'

# history
alias h='history'

# iptables
alias ipt='iptables -L -v -n'

# mounting
alias m.sda.das='mount /dev/sda /mnt/das'
alias m.sub.sda.bak='mount -o subvol=bak /dev/sda /bak'

# mkfs
alias mbf='mkfs.btrfs -f'
alias mbmd='mkfs.btrfs -m raid1 -d raid1'

# pam_snapper
alias pam.convert='bash /usr/lib/pam_snapper/pam_snapper_homeconvert.sh'
alias pam.config='bash /usr/lib/pam_snapper/pam_snapper_pamconfig.sh'
alias pam.useradd='bash /usr/lib/pam_snapper/pam_snapper_useradd.sh'
alias pam.userdel='bash /usr/lib/pam_snapper/pam_snapper_userdel.sh'

# podman
alias pod='podman'
alias podst='podman start'
alias podps='podman ps'
alias podpsa='podman ps -a'

# ssh

if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval `ssh-agent -s`
    ssh-add
fi

alias sa.w1='ssh-add ~/.ssh/w1'
alias sk.ed='ssh-keygen -t ed25519 -C "admin@woeiru.io"'
alias sc.ed='ssh-copy-id -i ~/.ssh/id_ed25519.pub root@192.168.178.110'
alias sa.ed='ssh-add ~/.ssh/id_ed25519'

alias sca='all-sca'
alias w1='sca r w1'

# system control aliases
alias y='systemctl'

# system configuration
alias v.samba.conf='vim /etc/samba/smb.conf'
alias v.sambausers='vim /etc/samba/smbusers'
alias v.firewall.conf='vim /etc/firewalld/firewalld.conf'
alias v.fstab='vim /etc/fstab'

# snapper
alias sl='snapper list'
alias sc='snapper create'
alias shl='osm-shl home'
alias shc='osm-shc home'
alias shd='osm-shd'

# Sysstat
alias sar='sar -d 1'
alias ios='iostat -x 1'

# SELinux
alias ses='sestatus -v'
alias seb='sudo semanage boolean -l'

# timedatectl
alias berlintime="timedatectl set-timezone Europe/Berlin"

# transactional update alias
alias tu='transactional-update'
alias tua='transactional-update apply'
alias tur='transactional-update reboot'
alias tuar='transactional-update apply && transactional-update reboot'

# tree view aliases
alias t='tree'
alias tt='tree -L 2'
alias ttt='tree -L 3'
alias tttt='tree -L 4'
alias ttttt='tree -L 5'

# vim
alias v='vim'
alias v.b="vim $INI_DIR/bashrc"
alias v.nw="vim $CON_DIR/node-w.md"

# unsorted
alias l='ls -Al'
