---
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Find all module files
      find:
        paths: "{{ playbook_dir }}/mods"
        patterns: "*.yml"
      register: module_files
      tags: always

    - name: Include all found modules
      include_tasks: "{{ item.path }}"
      loop: "{{ module_files.files | sort(attribute='path') }}"
      tags: always
