#!/bin/bash

    # Alias generation
    alias ali='$LAB_DIR/utl/cfg-ali'
    alias ap='ansible-playbook'

    # Bash
    alias b='bash'
    alias eb='exec bash'

    # BTRFS management
    alias bt='btrfs'
    alias btf='btrfs filesystem'

    # Cat (file viewing)
    alias c='cat'
    alias c.group='cat /etc/group'
    alias c.passwd='cat /etc/passwd'
    alias c.fstab='cat /etc/fstab'
    alias es.log='cat /mnt/bak/home/.es.log'

    # Directory navigation
    alias d='cd'
    alias ..='cd ..'
    alias dl="cd $LAB_DIR"

    alias d.samba='cd /etc/samba/'
    alias d.snapper='cd /etc/snapper/configs'
    alias d.pam='cd /usr/lib/pam_snapper'

    alias d.das='cd /mnt/das'
    alias d.nvm='cd /mnt/nvm'
    alias d.usb='cd /mnt/usb'

    # Disk usage
    alias u='du -bh -d1'
    alias uu='du -bh -d2'
    alias uuu='du -bh -d3'

    # Exit
    alias ee='exit'

    # Function chaining
    alias funcore='aux_ffl ana_laf "" "$LIB_CORE_DIR"'
    alias funops='aux_ffl ana_laf "" "$LIB_OPS_DIR"'
    alias fungen='aux_ffl ana_laf "" "$LIB_GEN_DIR"'
    alias var='aux_ffl ana_acu "" "$CFG_ENV_DIR" "$LIB_OPS_DIR" "$SRC_SET_DIR"'

    # Function makros
    alias v1='gpu_ptd ; qm start 211'

    # Git commands
    alias g='git'
    alias gs='git status'
    alias gd='git diff'
    alias gl='git ls-files | xargs cat | wc -l'
    alias ga='git add'
    alias gc='git commit'
    alias gcmb='git commit -m "base"'
    alias go='git push origin master'
    alias gp='git pull'
    alias gg='sys_gio'
    alias gr1='git revert HEAD~1'

    # History
    alias h='history'

    # IPTables
    alias ipt='iptables -L -v -n'

    # Mounting
    alias m.sda.das='mount /dev/sda /mnt/das'
    alias m.sub.sda.bak='mount -o subvol=bak /dev/sda /bak'

    # Filesystem creation
    alias mbf='mkfs.btrfs -f'
    alias mbmd='mkfs.btrfs -m raid1 -d raid1'

    # PAM Snapper commands
    alias pam.convert='bash /usr/lib/pam_snapper/pam_snapper_homeconvert.sh'
    alias pam.config='bash /usr/lib/pam_snapper/pam_snapper_pamconfig.sh'
    alias pam.useradd='bash /usr/lib/pam_snapper/pam_snapper_useradd.sh'
    alias pam.userdel='bash /usr/lib/pam_snapper/pam_snapper_userdel.sh'

    # Podman (container management)
    alias pod='podman'
    alias podst='podman start'
    alias podps='podman ps'
    alias podpsa='podman ps -a'

    # System control
    alias sy='systemctl'

    # System configuration file editing
    alias v.samba.conf='vim /etc/samba/smb.conf'
    alias v.sambausers='vim /etc/samba/smbusers'
    alias v.firewall.conf='vim /etc/firewalld/firewalld.conf'
    alias v.fstab='vim /etc/fstab'

    # Snapper (filesystem snapshot management)
    if [ -s "$DIR_LIB/ops/sto" ]; then
        source "$DIR_LIB/ops/sto"
        alias shl='sto_bfs_shl home'
        alias shc='sto_bfs_shc home'
        alias shd='sto_bfs_shd'
    fi

    # System statistics
    alias sar='sar -d 1'
    alias ios='iostat -x 1'

    # SELinux
    alias ses='sestatus -v'
    alias seb='sudo semanage boolean -l'

    # Time zone setting
    alias berlintime="timedatectl set-timezone Europe/Berlin"

    # Transactional update
    alias tu='transactional-update'
    alias tua='transactional-update apply'
    alias tur='transactional-update reboot'
    alias tuar='transactional-update apply && transactional-update reboot'

    # Dynamic tree function with line count
    
    tree_with_count() {
     local depth=${1:-0}
     local tree_cmd="tree"

     if [ $depth -gt 0 ]; then
           tree_cmd="tree -L $depth"
     fi

     $tree_cmd
     echo "Total lines: $(find . -type f -exec wc -l {} + | tail -n1 | awk '{print $1}')"
   }

    alias t='tree_with_count'
    alias tt='tree_with_count 2'
    alias ttt='tree_with_count 3'
    alias tttt='tree_with_count 4'
    alias ttttt='tree_with_count 5'
   
    # Vim
    alias v='vim'

    # File listing
    alias l='ls -Al'

    # Unsorted (you may want to organize these later)
    alias pr='kquitapp5 plasmashell && kstart5 plasmashell'
    alias gdi='git diff --no-index -- /dev/null'
    alias light='plasma-apply-lookandfeel -a org.kde.breeze.desktop && usr_ckp 1'
    alias dark='plasma-apply-lookandfeel -a org.kde.breezedark.desktop && usr_ckp 2'

    # Environment Management
    alias env='$LIB_GEN_DIR/env'
    alias env-dev='env switch-env dev'
    alias env-test='env switch-env test'
    alias env-staging='env switch-env staging'
    alias env-prod='env switch-env prod'
    alias env-stat='env status'
    alias env-list='env list'
    alias env-check='env validate'

    # DIC Operations Engine
    alias ops='$LAB_DIR/src/dic/ops'

    # History