#!/bin/bash
# ----------------------------------------------------------------------
# Functions:
#   a_xall: Installs NFS server packages, enables the NFS service, and 
#           creates a user account for NFS management.
#   b_xall: Configures NFS exports by setting up a shared folder with 
#           specified access permissions.
# ----------------------------------------------------------------------

# Define script location
DIR_SH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
FILE_SH="$(basename "${BASH_SOURCE[0]}")"
BASE_SH="${FILE_SH%.*}"

# Source menu file which provides logging and other core functionality
echo "[DEBUG] Sourcing: $(realpath "$DIR_SH/.menu")"
source "$(realpath "$DIR_SH/.menu")"

# Source DIC operations for intelligent parameter resolution
source "$DIR_SH/../dic/ops"

# Declare MENU_OPTIONS
declare -A MENU_OPTIONS
MENU_OPTIONS[a]="a_xall"
MENU_OPTIONS[b]="b_xall"

# Installs NFS server packages, enables the NFS service, and creates a user account for NFS management
a_xall() {
    ops sys ipa -j
    ops sys sdc -j
    ops sys ust -j
}

# Configures NFS exports by setting up a shared folder with specified access permissions
b_xall() {
    ops nfs set -j
}

# Handle script execution
if [ $# -eq 0 ]; then
    print_usage
    clean_exit 0       # Exit cleanly with status 0
else
    setup_main "$@"
    clean_exit $?
fi
