#!/bin/bash
# ----------------------------------------------------------------------
# Functions:
#   a_xall: Installs common system packages and configures global Git user credentials.
#   b_xall: Configures global Git user credentials.
# ----------------------------------------------------------------------

declare -g -a PACKAGES_ALL

# Define script location
DIR_SH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
FILE_SH="$(basename "${BASH_SOURCE[0]}")"
BASE_SH="${FILE_SH%.*}"

# Source aux file which provides logging and other core functionality
echo "[DEBUG] Sourcing: $(realpath "$DIR_SH/../../lib/laz/src")"
source "$(realpath "$DIR_SH/../../lib/laz/src")"

setup_source "$DIR_SH" "$FILE_SH" "$BASE_SH"

# Declare MENU_OPTIONS
declare -A MENU_OPTIONS
MENU_OPTIONS[a]="a_xall"
MENU_OPTIONS[b]="b_xall"

# Installs common system packages and configures global Git user credentials
a_xall() {
    sys-upa
    sys-ipa "${PACKAGES_DEV[@]}"
}

# Configures global Git user credentials
b_xall() {
    sys-gst "$GIT_USERNAME" "$GIT_USERMAIL"
    
}
# Handle script execution
if [ $# -eq 0 ]; then
    print_usage
    clean_exit 0       # Exit cleanly with status 0
else
    setup_main "$@"
    clean_exit $?
fi
