---
- name: Ensure .config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: Configure Plasma wallpaper settings in plasmarc
  ini_file:
    path: "{{ ansible_env.HOME }}/.config/plasmarc"
    section: Wallpapers
    option: usersWallpapers
    value: ""
    create: yes

- name: Configure Plasma desktop applets
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    block: |
      [Containments][1][ConfigDialog]
      DialogHeight=2532
      DialogWidth=1440

      [Containments][1][Wallpaper][org.kde.image][General]
      Image=/usr/share/wallpapers/Kay/
      PreviewImage=/usr/share/wallpapers/Kay/
      SlidePaths=/usr/share/wallpapers/

      [Containments][2][ConfigDialog]
      DialogHeight=2532
      DialogWidth=1440

      [Containments][2][Wallpaper][org.kde.image][General]
      Image=/usr/share/wallpapers/Kay/
      PreviewImage=/usr/share/wallpapers/Kay/
      SlidePaths=/usr/share/wallpapers/

      [Containments][3][ConfigDialog]
      DialogHeight=2532
      DialogWidth=1440

      [Containments][3][Wallpaper][org.kde.image][General]
      Image=/usr/share/wallpapers/Kay/
      PreviewImage=/usr/share/wallpapers/Kay/
      SlidePaths=/usr/share/wallpapers/
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - WALLPAPER SETTINGS"
