---
- name: Configure desk_1 preferences
  block:
    - name: Include Konsole configuration tasks
      include_tasks: konsole.yml

    - name: Include KWallet configuration tasks
      include_tasks: kwallet.yml
