---
- name: Configure desk_1 preferences
  block:
    - name: Include Konsole configuration tasks
      include_tasks: konsole.yml

    - name: Include wallpaper configuration tasks
      include_tasks: wallpaper.yml

    - name: Include KWallet configuration tasks
      include_tasks: kwallet.yml

    - name: Include shortcut configuration tasks
      include_tasks: shortcuts.yml
