---
- name: Ensure .config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: Ensure .local/share/kservices5 directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/share/kservices5"
    state: directory
    mode: '0755'

- name: Set global shortcuts using kwriteconfig5
  command: kwriteconfig5 --file kglobalshortcutsrc --group "{{ item.group }}" --key "{{ item.key }}" "{{ item.value }}"
  loop:
    - { group: "kwin", key: "_k_friendly_name", value: "KWin" }
    - { group: "kwin", key: "ExposeAll", value: "Ctrl+F10,Ctrl+F10,Toggle Present Windows (All desktops)" }
    - { group: "kwin", key: "Window Close", value: "Alt+F4,Alt+F4,Close Window" }
    - { group: "org.kde.kglobalaccel", key: "Sleep", value: "Meta+Del,Sleep,Sleep" }
    - { group: "plasmashell", key: "show-on-mouse-pos", value: "Meta+V,Meta+V,Show Clipboard Items at Mouse Position" }

- name: Create custom shortcut .desktop files
  copy:
    content: |
      [Desktop Entry]
      Name={{ item.name }}
      Exec={{ item.exec }}
      Type=Service
      X-KDE-ServiceTypes=KPluginInfo
      X-KDE-PluginInfo-EnabledByDefault=true
    dest: "{{ ansible_env.HOME }}/.local/share/kservices5/{{ item.filename }}"
  loop:
    - { name: "Switch to Dark Theme", exec: "bash -c 'theme-preset-dark'", filename: "switch_dark_theme.desktop" }
    - { name: "Switch to Light Theme", exec: "bash -c 'theme-preset-bright'", filename: "switch_light_theme.desktop" }

- name: Set custom shortcuts
  command: kwriteconfig5 --file kglobalshortcutsrc --group "{{ item.service }}" --key "_launch" "{{ item.shortcut }},none,{{ item.name }}"
  loop:
    - { service: "switch_dark_theme", shortcut: "Meta+End", name: "Switch to Dark Theme" }
    - { service: "switch_light_theme", shortcut: "Meta+Home", name: "Switch to Light Theme" }

- name: Set Konsole shortcut
  command: kwriteconfig5 --file kglobalshortcutsrc --group "org.kde.konsole.desktop" --key "_launch" "Meta+Return,none,Open Terminal"

- name: Reload Plasma Shell
  shell: kquitapp5 plasmashell && kstart5 plasmashell
  async: 300
  poll: 0
  changed_when: false

- name: Notify user about configuration changes
  debug:
    msg: "Shortcut configuration complete and Plasma shell has been reloaded. If shortcuts are still not working, you may need to log out and log back in."
