---
- name: Configure system preferences
  block:
    - name: Include wallpaper configuration tasks
      include_tasks: wallpaper.yml
    - name: Include KWallet configuration tasks
      include_tasks: kwallet.yml
    - name: Include shortcut configuration tasks
      include_tasks: shortcuts.yml
