---
- name: Ensure .config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: Configure global shortcuts
  ini_file:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: "kwin", option: "ExposeAll", value: "Ctrl+F10\\tLaunch (C)\\tMeta+Tab,Ctrl+F10\\tLaunch (C),Toggle Present Windows (All desktops)" }
    - { section: "kwin", option: "Window Close", value: "Alt+F4\\tMeta+Backspace,Alt+F4,Close Window" }
    - { section: "org.kde.kglobalaccel", option: "Sleep", value: "Meta+Del\\tSleep,Sleep,Suspend" }
    - { section: "plasmashell", option: "show-on-mouse-pos", value: "Meta+`\\tMeta+V,Meta+V,Show Clipboard Items at Mouse Position" }
    - { section: "org.kde.konsole.desktop", option: "_launch", value: "Meta+Return,none,Konsole" }

- name: Configure custom shortcuts
  ini_file:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    section: "services"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "[net.local.bash-2.desktop]_launch", value: "Meta+End" }
    - { option: "[net.local.bash.desktop]_launch", value: "Meta+Home" }

- name: Create custom shortcut files
  copy:
    content: "{{ item.content }}"
    dest: "{{ ansible_env.HOME }}/.local/share/applications/{{ item.filename }}"
    mode: '0644'
  loop:
    - filename: "net.local.bash-2.desktop"
      content: |
        [Desktop Entry]
        Exec=bash -c -i "theme-preset-dark"
        Name=
        NoDisplay=true
        StartupNotify=false
        Type=Application
        X-KDE-GlobalAccel-CommandShortcut=true
    - filename: "net.local.bash.desktop"
      content: |
        [Desktop Entry]
        Exec=bash -c -i "theme-preset-bright"
        Name=
        NoDisplay=true
        StartupNotify=false
        Type=Application
        X-KDE-GlobalAccel-CommandShortcut=true

- name: Ensure .local/state directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/state"
    state: directory
    mode: '0755'

- name: Update plasmashellstaterc
  ini_file:
    path: "{{ ansible_env.HOME }}/.local/state/plasmashellstaterc"
    section: "KickerRunnerManager][History"
    option: "a19edca3-f987-4565-9b0d-339920995a1f"
    value: "shortcuts,kde wallet,wallet,kde,kdewa,walle,kdewall"
