---
- name: Ensure .config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: Configure global shortcuts
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    regexp: "^{{ item.option }}="
    line: "{{ item.option }}={{ item.value }}"
  loop:
    - { option: "ExposeAll", value: "Ctrl+F10\\tLaunch (C)\\tMeta+Tab,Ctrl+F10\\tLaunch (C),Toggle Present Windows (All desktops)" }
    - { option: "Window Close", value: "Alt+F4\\tMeta+Backspace,Alt+F4,Close Window" }
    - { option: "Sleep", value: "Meta+Del,Sleep,Sleep,Suspend" }
    - { option: "show-on-mouse-pos", value: "Meta+`\\tMeta+V,Meta+V,Show Clipboard Items at Mouse Position" }

- name: Remove existing custom shortcuts block
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    block: ""
    marker: "# {mark} ANSIBLE MANAGED BLOCK - CUSTOM SHORTCUTS"
    state: absent

- name: Configure custom shortcuts
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    block: |

      [services][net.local.bash-2.desktop]
      _launch=Meta+End,none,Switch to Dark Theme

      [services][net.local.bash.desktop]
      _launch=Meta+Home,none,Switch to Light Theme

      [services][org.kde.konsole.desktop]
      NewWindow=Meta+Return

    marker: "# {mark} ANSIBLE MANAGED BLOCK - CUSTOM SHORTCUTS"
    insertafter: EOF

- name: Create custom shortcut files
  copy:
    content: "{{ item.content }}"
    dest: "{{ ansible_env.HOME }}/.local/share/applications/{{ item.filename }}"
    mode: '0644'
  loop:
    - filename: "net.local.bash-2.desktop"
      content: |
        [Desktop Entry]
        Exec=bash -c -i "theme-preset-dark"
        Name=Switch to Dark Theme
        NoDisplay=true
        StartupNotify=false
        Type=Application
        X-KDE-GlobalAccel-CommandShortcut=true
    - filename: "net.local.bash.desktop"
      content: |
        [Desktop Entry]
        Exec=bash -c -i "theme-preset-bright"
        Name=Switch to Light Theme
        NoDisplay=true
        StartupNotify=false
        Type=Application
        X-KDE-GlobalAccel-CommandShortcut=true

- name: Notify user to restart KDE
  debug:
    msg: "Shortcut configuration complete. Please restart your KDE session (log out and log back in) to ensure all changes take effect."
