---
- name: Configure Icons-and-Text Task Manager Widget
  ini_file:
    path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    section: plasmashell
    option: "activate widget 30"
    value: ",none,Activate Icons-and-Text Task Manager Widget"

- name: Configure panel thickness
  ini_file:
    path: "{{ ansible_env.HOME }}/.config/plasmashellrc"
    section: "PlasmaViews][Panel 2][Defaults"
    option: "thickness"
    value: "40"

- name: Restart Plasma to apply changes
  command: kquitapp5 plasmashell && kstart5 plasmashell
  async: 45
  poll: 0
