---

- name: Configure panel thickness
  ini_file:
    path: "{{ ansible_env.HOME }}/.config/plasmashellrc"
    section: "PlasmaViews][Panel 2][Defaults"
    option: "thickness"
    value: "40"

- name: Notify user about configuration changes
  debug:
    msg: |
      Configuration files have been updated. Changes will take effect after you log out and log back in, or after your next system restart.

- name: Restart Plasma shell
  shell: kquitapp5 plasmashell && kstart5 plasmashell
