#!/bin/bash

# Define the directory of the script using a POSIX-compliant method
DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" >/dev/null 2>&1 && pwd)"
PARENT_DIR="/root/lab"

# Main sourcing function for env files
source_env() {
    log "lvl-2" "Starting ${FUNCNAME[0]} ()"
    # Source env modules
    local env_modules=("env2")
    log "lvl-3" "Sourcing files $env_var_name(${env_modules[*]})"
    for module in "${env_modules[@]}"; do
        if ! source_helper "$DIR/$module"; then
            log "lvl-2" "Error: Failed to source $module" | tee -a "$ERROR_LOG" >&2
            return 1
        fi
    done
    log "lvl-3" "All env modules sourced successfully"
    return 0
}

# Main execution setup for env files
execution_env() {
    log "lvl-2" "Starting ${FUNCNAME[0]} ()"
    # Check if required functions exist before calling them
    local required_functions=("set_ssh")
    for func in "${required_functions[@]}"; do
        if type "$func" &>/dev/null; then
            log "lvl-3" "Executing $func"
            if ! $func; then
                log "lvl-2" "Error: $func failed" | tee -a "$ERROR_LOG" >&2
                return 1
            fi
        else
            log "lvl-3" "Warning: $func function not found." | tee -a "$ERROR_LOG" >&2
            return 1
        fi
    done
    return 0
}

# Main execution
main_env() {
    local source_success=0
    local execution_success=0

    if source_env; then
        export SOURCE_ENV_SUCCESS=1
        source_success=1
    else
        unset SOURCE_ENV_SUCCESS
    fi

    if execution_env; then
        export EXECUTION_ENV_SUCCESS=1
        execution_success=1
    else
        unset EXECUTION_ENV_SUCCESS
    fi

    if [[ $source_success -eq 1 && $execution_success -eq 1 ]]; then
        export ENV_SOURCED=1
    else
        unset ENV_SOURCED
    fi

    if [[ -z "${SOURCE_ENV_SUCCESS}" ]]; then
        log "lvl-2" "Error: Source env failed." | tee -a "$ERROR_LOG" >&2
    fi

    if [[ -z "${EXECUTION_ENV_SUCCESS}" ]]; then
        log "lvl-2" "Error: Execution env failed." | tee -a "$ERROR_LOG" >&2
    fi

    if [[ -z "${ENV_SOURCED}" ]]; then
        log "lvl-2" "Error: Overall environment sourcing failed." | tee -a "$ERROR_LOG" >&2
        return 1
    else
        log "lvl-2" "Env setup completed successfully."
        return 0
    fi
}
