---
- hosts: localhost
  vars:
    config_editor: true
    config_system_prefs: true
  roles:
    - { role: editor_config, when: config_editor | bool, tags: ['editor'] }
    - { role: system_preferences, when: config_system_prefs | bool, tags: ['system'] }
  # Commented roles can be uncommented and added similarly when needed
  # - { role: development_env, when: config_dev_env | bool, tags: ['dev'] }
  # - { role: gui_apps, when: config_gui | bool, tags: ['gui'] }
  # - { role: security_config, when: config_security | bool, tags: ['security'] }
  # - { role: shell_config, when: config_shell | bool, tags: ['shell'] }
